config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  

  get 'store/index'
  get 'cart', to: 'orders#cart', as: :cart
  get 'checkout', to: 'orders#checkout', as: :checkout
  get 'complete_order', to: 'orders#complete_order', as: :complete_order
  get 'account', to: 'users#show', as: :account

  resources :payments, only: %i[new create index]
  resources :payment_method

  post 'add_to_basket', to: 'product#add_to_basket', as: :add_to_basket
  post 'select_store/:id', to: 'store#select_store', as: :select_store

  resources :products, controller: 'product', only: %i[index new create]
  resources :categories, controller: 'category', only: %i[index new create]
  resources :orders do
    member do
      get 'check_in'
    end
  end
  resources :order_items
  resources :carts, only: %i[index]
  resources :manage, only: %i[index]
  resources :home
  get 'user_home', to: 'home#user_home', as: :user_home
  resources :admin, only: %i[index]

  scope 'admin' do
    resources :mqtt_log, only: %i[index]
  end

  resources :store, only: %i[index show]

  scope ':store_name', as: 'store_name' do
    resources :menu, only: %i[index] do
      collection do
        resources :category, only: %i[index show], param: :category_name
      end
    end
    resources :product, only: %i[show], param: :product_name
  end

  scope 'admin' do 
    get 'export_catalogue', to: 'product#export', as: :export_catalogue
    resources :users, only: %i[index edit update destroy] do
      member do
      patch 'update_role', to: 'users#update_role', as: :update_role
      end
    end
    resources :roles
    scope ':store_name', as: 'store_name' do
      get '/', to: 'admin#show', as: :admin_show
      scope 'availability' do
        resources :products, controller: 'admin/availability/products', only: %i[index update], param: :store_name, as: :product_availability
        patch 'products/update', to: 'admin/availability/products#update'
        resources :ingredients, controller: 'admin/availability/ingredients', only: %i[index update], param: :store_name, as: :ingredient_availability
        patch 'ingredients/update', to: 'admin/availability/ingredients#update'
      end
    end
  end
  scope 'webhooks' do
    post 'payment_intents', to: 'stripe_webhooks#payment_intents'
  end
end

app/views/layouts/user_navigation/_desktop.html.slim
.col-12.bg-secondary.shadow.d-flex.justify-content-between.p-2
  .d-flex.justify-content-start.gap-4
    = link_to root_path, class: "text-decoration-none text-dark" do
      .col-12.d-flex.justify-content-center
        i.h4.fa-solid.fa-home.no-h-padding
        h3.no-h-padding.brand-font.ps-2 Home
    
    = link_to store_index_path, class: "text-decoration-none text-dark" do
      .col-12.d-flex.justify-content-center
        i.fa-solid.fa-location-dot.h4.no-h-padding
        h3.no-h-padding.brand-font.ps-2 Find a Store

    = link_to store_index_path, class: "text-decoration-none text-dark" do
      .col-12.d-flex.justify-content-center
        i.fa-solid.fa-store.h4.no-h-padding
        h3.no-h-padding.brand-font.ps-2 Order Now

  .d-flex.justify-content-end.gap-3
    = link_to checkout_path, class: "text-decoration-none text-dark" do
      .col-12.d-flex.justify-content-center
        i.fa-solid.fa-shopping-basket.h3.no-h-padding

    = link_to account_path, class: "text-decoration-none text-dark" do
      .col-12.d-flex.justify-content-center
        i.fa-solid.fa-user.h3.no-h-padding

  
    

app/views/layouts/user_navigation/_mobile.html.slim
.col-12.d-flex.justify-content-center.fixed-bottom
  .col-12.bg-white.reverse-shadow.d-flex style="z-index: 1000; max-width:600px;"
    .d-flex.col-12.justify-content-between.align-items-center.ps-4.pe-4.p-2
      .d-flex.flex-column.justify-content-center.align-items-center
        = link_to root_path, class: "text-decoration-none text-dark" do
          .col-12.d-flex.justify-content-center
            i.fa-solid.fa-home.display-4.no-h-padding
          h3.text-dark.no-h-padding.brand-font Home
      .d-flex.flex-column.justify-content-center.align-items-center
        = link_to store_index_path, class: "text-decoration-none text-dark" do
          .col-12.d-flex.justify-content-center
            i.fa-solid.fa-store.display-4.no-h-padding
          h3.text-dark.no-h-padding.brand-font Store
      .d-flex.flex-column.justify-content-center.align-items-center
        = link_to checkout_path, class: "text-decoration-none text-dark" do
          .col-12.d-flex.justify-content-center
            i.fa-solid.fa-shopping-basket.display-4.no-h-padding
          h3.text-dark.no-h-padding.brand-font Checkout
      .d-flex.flex-column.justify-content-center.align-items-center
        = link_to account_path, class: "text-decoration-none text-dark" do
          .col-12.d-flex.justify-content-center
            i.fa-solid.fa-user.display-4.no-h-padding
          h3.text-dark.no-h-padding.brand-font Account

= render "layouts/store_banner"