config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  

  get 'store/index'
  get 'cart', to: 'orders#cart', as: :cart
  get 'checkout', to: 'orders#checkout', as: :checkout
  get 'complete_order', to: 'orders#complete_order', as: :complete_order
  get 'account', to: 'users#show', as: :account

  resources :payments, only: %i[new create index]
  resources :payment_method

  post 'add_to_basket', to: 'product#add_to_basket', as: :add_to_basket
  post 'select_store/:id', to: 'store#select_store', as: :select_store

  resources :products, controller: 'product', only: %i[index new create]
  resources :categories, controller: 'category', only: %i[index new create]
  resources :orders do
    member do
      get 'check_in'
    end
  end
  resources :order_items
  resources :carts, only: %i[index]
  resources :manage, only: %i[index]
  resources :home
  get 'user_home', to: 'home#user_home', as: :user_home
  resources :admin, only: %i[index]

  scope 'admin' do
    resources :mqtt_log, only: %i[index]
  end

  resources :store, only: %i[index show]

  scope ':store_name', as: 'store_name' do
    resources :menu, only: %i[index] do
      collection do
        resources :category, only: %i[index show], param: :category_name
      end
    end
    resources :product, only: %i[show], param: :product_name
  end

  scope 'admin' do 
    get 'export_catalogue', to: 'product#export', as: :export_catalogue
    resources :users, only: %i[index edit update destroy] do
      member do
      patch 'update_role', to: 'users#update_role', as: :update_role
      end
    end
    resources :roles
    scope ':store_name', as: 'store_name' do
      get '/', to: 'admin#show', as: :admin_show
      scope 'availability' do
        resources :products, controller: 'admin/availability/products', only: %i[index update], param: :store_name, as: :product_availability
        patch 'products/update', to: 'admin/availability/products#update'
        resources :ingredients, controller: 'admin/availability/ingredients', only: %i[index update], param: :store_name, as: :ingredient_availability
        patch 'ingredients/update', to: 'admin/availability/ingredients#update'
      end
    end
  end
  scope 'webhooks' do
    post 'payment_intents', to: 'stripe_webhooks#payment_intents'
  end
end

app/views/admin/_admin_dashboard_link.html.slim
.col-12.d-flex.justify-content-start.p-2
  = link_to admin_index_path, class: '' do
    i.fa-solid.fa-arrow-left.pe-1
    | Admin Dashboard
  

app/views/admin/index.html.slim
.col-12
  h1.p-1.brand-font Tools
  .col-12.d-flex.ps-2.pe-2.gap-2 style="overflow-x: auto;"
    .card.col-3
      .card-body
        h3.card-title Stores
        p.card-subtitle.text-muted Manage stores and their product / ingredient availability
        = link_to 'Stores', admin_index_path, class: 'card-link'
    .card.col-3
      .card-body
        h3.card-title Users
        p.card-subtitle.text-muted Manage Users
        = link_to 'Users', users_path, class: 'card-link'

    .card.col-3
      .card-body
        h3.card-title Products
        p.card-subtitle.text-muted Manage Products for all stores.
        p.card-text Add, change and remove products for the entire platform
        = link_to 'products', admin_index_path, class: 'card-link'
        = link_to 'export', export_catalogue_path, class: 'card-link'
    
    .card.col-3
      .card-body
        h3.card-title Ingredients
        p.card-subtitle.text-muted Manage Ingredients for all stores.
        p.card-text Add, change and remove ingredients for the entire platform
        = link_to 'products', admin_index_path, class: 'card-link'


hr 
.col-12.d-flex.justify-content-center
  .col-10.m-3.p-2.bg-white.rounded.shadow
    h1.brand-font Stores
    table.table.table-striped
      thead
        tr
          th Store ID
          th Store Name
          th Address
          th Orders Count
          th Revenue
          th Actions
      tbody
        - @stores.each do |store|
          tr
            td = store.id
            td = store.name
            td = "#{store.address.number} #{store.address.street}, #{store.address.city}, #{store.address.postcode}" 
            td = store.orders.count
            td 
            td = link_to store_name_admin_show_path(store_name: store.slug), class: 'btn btn-primary' do
              i.fas.fa-eye

app/views/admin/show.html.slim
h1.brand-font.text-center = "#{@store.name} Admin Panel"

.col-12.d-flex.justify-content-center
  .col-9.d-flex.justify-content-center.gap-3
    = link_to store_name_product_availability_index_path(), class: "text-dark" do
      h5 Product Availability 
    = link_to store_name_ingredient_availability_index_path(), class: "text-dark" do
      h5 Ingredient Availability 