config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  

  get 'store/index'
  get 'cart', to: 'orders#cart', as: :cart
  get 'checkout', to: 'orders#checkout', as: :checkout
  get 'complete_order', to: 'orders#complete_order', as: :complete_order
  get 'account', to: 'users#show', as: :account

  resources :payments, only: %i[new create index]
  resources :payment_method

  post 'add_to_basket', to: 'product#add_to_basket', as: :add_to_basket
  post 'select_store/:id', to: 'store#select_store', as: :select_store

  resources :products, controller: 'product', only: %i[index new create]
  resources :categories, controller: 'category', only: %i[index new create]
  resources :orders do
    member do
      get 'check_in'
    end
  end
  resources :order_items
  resources :carts, only: %i[index]
  resources :manage, only: %i[index]
  resources :home
  get 'user_home', to: 'home#user_home', as: :user_home
  resources :admin, only: %i[index]

  scope 'admin' do
    resources :mqtt_log, only: %i[index]
  end

  resources :store, only: %i[index show]

  scope ':store_name', as: 'store_name' do
    resources :menu, only: %i[index] do
      collection do
        resources :category, only: %i[index show], param: :category_name
      end
    end
    resources :product, only: %i[show], param: :product_name
  end

  scope 'admin' do 
    get 'export_catalogue', to: 'product#export', as: :export_catalogue
    resources :users, only: %i[index edit update destroy] do
      member do
      patch 'update_role', to: 'users#update_role', as: :update_role
      end
    end
    resources :roles
    scope ':store_name', as: 'store_name' do
      get '/', to: 'admin#show', as: :admin_show
      scope 'availability' do
        resources :products, controller: 'admin/availability/products', only: %i[index update], param: :store_name, as: :product_availability
        patch 'products/update', to: 'admin/availability/products#update'
        resources :ingredients, controller: 'admin/availability/ingredients', only: %i[index update], param: :store_name, as: :ingredient_availability
        patch 'ingredients/update', to: 'admin/availability/ingredients#update'
      end
    end
  end
  scope 'webhooks' do
    post 'payment_intents', to: 'stripe_webhooks#payment_intents'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :nullify
  has_many :user_roles, dependent: :destroy
  has_many :roles, through: :user_roles
  after_create_commit :create_stripe_user

  validates :first_name, presence: true
  validates :last_name, presence: true

  def basket
    orders.where(state: %i[pending on_checkout]).last || orders.create(state: :pending)
  end

  def recipe_name
    "#{first_name.capitalize} #{last_name[0].capitalize}."
  end

  def create_stripe_user
    # rubocop:disable Layout/FirstHashElementIndentation
    return if Rails.env.test?

    customer = Stripe::Customer.create({
      email: email,
      metadata: {
        user_id: id
      }
    })
    self.stripe_id = customer.id
    save
    # rubocop:enable Layout/FirstHashElementIndentation
  end

  def add_role(role)
    return if roles.exists?(id: role)

    user_roles.create(role: Role.find_by(id: role))
  end

  def remove_role(role)
    return unless roles.exists?(id: role)

    user_roles.where(role: Role.find_by(id: role)).destroy_all
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

# rubocop:disable Style/ClassAndModuleChildren

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # rubocop:disable Lint/UselessMethodDefinition
  def create
    super
  end
  # rubocop:enable Lint/UselessMethodDefinition

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end
# rubocop:enable Style/ClassAndModuleChildren

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  # before_action :authorize!, except: [:show]

  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update_role
    params = role_params
    @user = User.find(params[:id])
    if params[:commit].downcase == 'add role'
      @user.add_role(params[:role_id])
    elsif params[:commit].downcase == 'remove role'
      @user.remove_role(params[:role_id])
    end
    redirect_to user_path(@user), notice: 'Role updated successfully'
  end

  private

  def role_params
    params.permit(:role_id, :commit, :id)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/edit.html.slim
.col-12.p-3
  .col-12.bg-white.rounded.shadow.p-3
    p.no-h-padding.brand-font User Details
    h1.no-h-padding = @user.email
    hr
    .d-flex.flex-wrap
      .col-12.col-md-6.col-lg-4.p-3
        .row
          .col.mb-4
            h6.no-h-padding Name
            hr.no-h-padding
            h6.fw-bold Place Holder Name
          .col.mb-4
            h6.no-h-padding Email
            hr.no-h-padding
            h6.fw-bold = @user.email
        .row
          .col.mb-4
            h6.no-h-padding Joined at:
            hr.no-h-padding
            h6.fw-bold = @user.created_at.strftime("%B %d, %Y")
          .col.mb-4
            h6.no-h-padding Last login:
            hr.no-h-padding
            h6.fw-bold Place holder
      .col-12.col-md-6.col-lg-8.p-3
        h3 Roles 
        hr.no-h-padding
        - @user.roles.each do |role|
          span.badge.bg-primary.m-1
            .col.d-flex
              .btn-none.text-white.p-0
                = role.name
              = button_to "X", update_role_user_path(@user), method: :patch, params: { action: "remove", role_id: role.id, commit: "remove role" }, class: "btn-none text-white p-0 ps-2 fw-bold"
        button.badge.bg-primary.m-1 type="button" onclick="document.getElementById('role-dialog').showModal()" Add Role
              
    hr
    .col-12
      p.no-h-padding.brand-font Past Orders
      table.table.table-striped
        thead
          tr
            th Order ID
            th Status
            th Total
            th Created at
        tbody
          - @user.orders.each do |order|
            tr
              td = order.id
              td = order.state
              td = number_to_currency(order.total, :unit => "£")
              td = order.created_at.strftime("%B %d, %Y")

dialog#role-dialog class="bg-light rounded-3 border border-none"
  div class="modal-content"
    div class="modal-header d-flex justify-content-between"
      h2 class="modal-title" id="role-dialog-title"
      button type="button" class="btn-close" onclick="document.getElementById('role-dialog').close()" aria-label="Close"
    hr
    div class="modal-body" id="role-dialog-body"
      .col-12.p-3
        h2.no-h-padding.brand-font Add Role To User
        = form_with url: update_role_user_path(@user), method: :patch, local: true do |f|
          = f.hidden_field :action, value: "add"
          .mb-3
            = f.label :role_id, "Select Role", class: "form-label"
            = f.select :role_id, Role.all.collect { |role| [role.name, role.id] }, {}, class: "form-select shadow"
          .d-flex.justify-content-center
            = f.submit "Add Role", class: "btn btn-primary"

app/views/users/index.html.slim
= render "admin/admin_dashboard_link"

.col-12
  h1.p-1.brand-font Tools
  .col-12.d-flex.ps-2.pe-2.gap-2 style="overflow-x: auto;"
    .card.col-3
      .card-body
        h3.card-title Role
        p.card-subtitle.text-muted Manage Users
        = link_to 'Manage Roles', roles_path, class: 'card-link'

.col-12.d-flex.justify-content-center
  .col-10.m-3.p-2.bg-white.rounded.shadow
    h1.brand-font Users
    table.table.table-striped
      thead
        tr
          th User ID
          th Email
          th Roles
          th Actions
      tbody
        - @users.each do |user|
          tr
            td = user.id
            td = user.email
            td 
              - user.roles.each do |role|
                span.badge.bg-primary.m-1 = role.name
            td = link_to 'Edit', edit_user_path(user), class: 'btn btn-primary'

app/views/users/show.html.slim
.container-fluid.px-2.px-md-4.pt-4
  .row.g-2.mb-3.justify-content-center
    .col-12.d-flex.flex-wrap.gap-2.justify-content-center
      / = link_to "Your Details", account_path, class: "btn btn-light brand-font"
      / = link_to "Your Payment Methods", payment_method_index_path, class: "btn btn-light brand-font"

  .row.g-3
    .col-12.col-lg-4.mb-3
      .bg-white.rounded.shadow.p-3.h-100
        h2.brand-font.text-center.mb-3 Your Details
        hr
        table.table.table-borderless.mb-3
          tbody
            tr
              td.fw-bold Email:
              td = @user.email
            tr
              td.fw-bold Joined:
              td = @user.created_at.strftime("%B %d, %Y")
        .d-flex.justify-content-center.gap-2.mt-3
          = link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-dark brand-font"
          = link_to "Edit Details", edit_user_registration_path, class: "btn btn-dark brand-font"

    .col-12.col-lg-8
      .bg-white.rounded.shadow.p-3.h-100
        h2.brand-font.text-center.mb-3 Past Orders
        table.table.table-hover.text-center
          thead
            tr
              th.brand-font Order Number
              th.brand-font Order Date
              th.brand-font Order Total
              th.brand-font View Items
          tbody
            - @user.orders.each do |order|
              tr
                td = order.id
                td = order.created_at.strftime("%B %d, %Y")
                td £#{order.order_items.sum { |item| item.product.price }}
                td
                  = link_to order_path(order), class: "btn btn-dark btn-sm", title: "View Order" do
                    i.fas.fa-eye