config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  

  get 'store/index'
  get 'cart', to: 'orders#cart', as: :cart
  get 'checkout', to: 'orders#checkout', as: :checkout
  get 'complete_order', to: 'orders#complete_order', as: :complete_order
  get 'account', to: 'users#show', as: :account

  resources :payments, only: %i[new create index]
  resources :payment_method

  post 'add_to_basket', to: 'product#add_to_basket', as: :add_to_basket
  post 'select_store/:id', to: 'store#select_store', as: :select_store

  resources :products, controller: 'product', only: %i[index new create]
  resources :categories, controller: 'category', only: %i[index new create]
  resources :orders do
    member do
      get 'check_in'
    end
  end
  resources :order_items
  resources :carts, only: %i[index]
  resources :manage, only: %i[index]
  resources :home
  get 'user_home', to: 'home#user_home', as: :user_home
  resources :admin, only: %i[index]

  scope 'admin' do
    resources :mqtt_log, only: %i[index]
  end

  resources :store, only: %i[index show]

  scope ':store_name', as: 'store_name' do
    resources :menu, only: %i[index] do
      collection do
        resources :category, only: %i[index show], param: :category_name
      end
    end
    resources :product, only: %i[show], param: :product_name
  end

  scope 'admin' do 
    get 'export_catalogue', to: 'product#export', as: :export_catalogue
    resources :users, only: %i[index edit update destroy] do
      member do
      patch 'update_role', to: 'users#update_role', as: :update_role
      end
    end
    resources :roles
    scope ':store_name', as: 'store_name' do
      get '/', to: 'admin#show', as: :admin_show
      scope 'availability' do
        resources :products, controller: 'admin/availability/products', only: %i[index update], param: :store_name, as: :product_availability
        patch 'products/update', to: 'admin/availability/products#update'
        resources :ingredients, controller: 'admin/availability/ingredients', only: %i[index update], param: :store_name, as: :ingredient_availability
        patch 'ingredients/update', to: 'admin/availability/ingredients#update'
      end
    end
  end
  scope 'webhooks' do
    post 'payment_intents', to: 'stripe_webhooks#payment_intents'
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  # after_action :record_event
  before_action :authenticate_user!, only: [:user_home]

  def index
    return unless user_signed_in?
    redirect_to user_home_path
  end

  def user_home
    @stores = Store.all
    @product = Product.first
  end

  private

  def record_event
    return if current_user.blank?

    GoogleRetailTagService.new(current_user).home_event
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/index.html.slim
.hero
  .landing-page.mt-3
    = image_tag  "hero.png", class: "img-fluid hero-img"
    .wav-devider
      = image_tag "green-wavy-devider.svg", class: "wavy-devider", width:"100%"

.col-12
  
  
  .col-12.bg-green.pb-5
    h1.brand-font.text-light.text-center Welcome to Alpaca Peruleon Cafe
    .col-12.d-flex.justify-content-center.align-items-center
      hr.text-light.border-3.shadow.col-8
    .col-12.d-flex.flex-row.flex-wrap.justify-content-between
      .col-12.col-md-6.col-lg-6.d-flex.justify-content-center
        .col-12.d-flex.flex-column.justify-content-center.align-items-center
          .display-3.brand-font.text-light.text-center
            | Start your day right
          = link_to "Order Now", store_index_path, class: "btn btn-organge btn-lg btn-block mt-3 col-6 brand-font text-light text-center"
          = link_to "View Our Menu", store_index_path, class: "text-light"
          
          

      / .col-12.col-md-6.col-lg-6.d-flex.justify-content-center
      /   .col-8.d-flex.flex-column.justify-content-center.align-items-center
      /     h1.brand-font.text-light May we tempt you with
      /     - @recommended_products.each do |product|
      /       .bg-light.p-3.m-3.shadow.rounded-normal.col-8
      /         = image_tag product.image, class: "img-fluid rounded lazyload"
      /         h3.brand-font = product.name
      /         p = "£#{product.price}"

      /         .d-flex.flex-row.justify-content-center.gap-3.brand-font
      /           - if current_user
      /             = button_to 'Add to Order', add_to_basket_url(product: product), method: :post, class: "btn btn-primary"
      /           = link_to product_path(product), class: "btn btn-secondary flex-fill" 
      /             | view 
      /             - if current_user
      /               | & Customise

    .col-12.d-flex.justify-content-center.align-items-center
      hr.text-light.border-3.shadow.col-8
.col-12
  = image_tag "green-wavy-devider.svg", class: "img-fluid col-12 wavy-devider-reverse"

app/views/home/user_home.slim
.d-block.d-md-block.d-lg-none
  = render 'home/user_home/mobile'
.d-none.d-md-none.d-lg-block
  = render 'home/user_home/desktop'